# Generated by Django 4.0.3 on 2022-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
